import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/_components/app/navbar";
import { inter } from "@/_libs/fonts";

export const metadata: Metadata = {
  title: "ashokasec/ui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
